package com.riccardo.mapper;

import com.riccardo.models.Immatricolazioni;
import com.riccardo.models.ImmatricolazioniExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ImmatricolazioniMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.immatricolazioni
     *
     * @mbg.generated Sat Oct 21 12:44:24 CEST 2023
     */
    long countByExample(ImmatricolazioniExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.immatricolazioni
     *
     * @mbg.generated Sat Oct 21 12:44:24 CEST 2023
     */
    int deleteByExample(ImmatricolazioniExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.immatricolazioni
     *
     * @mbg.generated Sat Oct 21 12:44:24 CEST 2023
     */
    int deleteByPrimaryKey(Integer idImmatricolazione);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.immatricolazioni
     *
     * @mbg.generated Sat Oct 21 12:44:24 CEST 2023
     */
    int insert(Immatricolazioni row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.immatricolazioni
     *
     * @mbg.generated Sat Oct 21 12:44:24 CEST 2023
     */
    int insertSelective(Immatricolazioni row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.immatricolazioni
     *
     * @mbg.generated Sat Oct 21 12:44:24 CEST 2023
     */
    List<Immatricolazioni> selectByExampleWithRowbounds(ImmatricolazioniExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.immatricolazioni
     *
     * @mbg.generated Sat Oct 21 12:44:24 CEST 2023
     */
    List<Immatricolazioni> selectByExample(ImmatricolazioniExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.immatricolazioni
     *
     * @mbg.generated Sat Oct 21 12:44:24 CEST 2023
     */
    Immatricolazioni selectByPrimaryKey(Integer idImmatricolazione);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.immatricolazioni
     *
     * @mbg.generated Sat Oct 21 12:44:24 CEST 2023
     */
    int updateByExampleSelective(@Param("row") Immatricolazioni row, @Param("example") ImmatricolazioniExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.immatricolazioni
     *
     * @mbg.generated Sat Oct 21 12:44:24 CEST 2023
     */
    int updateByExample(@Param("row") Immatricolazioni row, @Param("example") ImmatricolazioniExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.immatricolazioni
     *
     * @mbg.generated Sat Oct 21 12:44:24 CEST 2023
     */
    int updateByPrimaryKeySelective(Immatricolazioni row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.immatricolazioni
     *
     * @mbg.generated Sat Oct 21 12:44:24 CEST 2023
     */
    int updateByPrimaryKey(Immatricolazioni row);
}