package com.riccardo.mapper;

import com.riccardo.models.Moto;
import com.riccardo.models.MotoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.moto
     *
     * @mbg.generated Sat Oct 21 12:44:24 CEST 2023
     */
    long countByExample(MotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.moto
     *
     * @mbg.generated Sat Oct 21 12:44:24 CEST 2023
     */
    int deleteByExample(MotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.moto
     *
     * @mbg.generated Sat Oct 21 12:44:24 CEST 2023
     */
    int deleteByPrimaryKey(Integer idMoto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.moto
     *
     * @mbg.generated Sat Oct 21 12:44:24 CEST 2023
     */
    int insert(Moto row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.moto
     *
     * @mbg.generated Sat Oct 21 12:44:24 CEST 2023
     */
    int insertSelective(Moto row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.moto
     *
     * @mbg.generated Sat Oct 21 12:44:24 CEST 2023
     */
    List<Moto> selectByExampleWithRowbounds(MotoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.moto
     *
     * @mbg.generated Sat Oct 21 12:44:24 CEST 2023
     */
    List<Moto> selectByExample(MotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.moto
     *
     * @mbg.generated Sat Oct 21 12:44:24 CEST 2023
     */
    Moto selectByPrimaryKey(Integer idMoto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.moto
     *
     * @mbg.generated Sat Oct 21 12:44:24 CEST 2023
     */
    int updateByExampleSelective(@Param("row") Moto row, @Param("example") MotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.moto
     *
     * @mbg.generated Sat Oct 21 12:44:24 CEST 2023
     */
    int updateByExample(@Param("row") Moto row, @Param("example") MotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.moto
     *
     * @mbg.generated Sat Oct 21 12:44:24 CEST 2023
     */
    int updateByPrimaryKeySelective(Moto row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.moto
     *
     * @mbg.generated Sat Oct 21 12:44:24 CEST 2023
     */
    int updateByPrimaryKey(Moto row);
}