package com.riccardo.models;

import java.util.Date;

public class Immatricolazioni {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.immatricolazioni.id_immatricolazione
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	private Integer idImmatricolazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.immatricolazioni.targa
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	private String targa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.immatricolazioni.id_moto
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	private Integer idMoto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.immatricolazioni.data_immatricolazione
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	private Date dataImmatricolazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.immatricolazioni.id_immatricolazione
	 * @return  the value of public.immatricolazioni.id_immatricolazione
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public Integer getIdImmatricolazione() {
		return idImmatricolazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.immatricolazioni.id_immatricolazione
	 * @param idImmatricolazione  the value for public.immatricolazioni.id_immatricolazione
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public void setIdImmatricolazione(Integer idImmatricolazione) {
		this.idImmatricolazione = idImmatricolazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.immatricolazioni.targa
	 * @return  the value of public.immatricolazioni.targa
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public String getTarga() {
		return targa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.immatricolazioni.targa
	 * @param targa  the value for public.immatricolazioni.targa
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public void setTarga(String targa) {
		this.targa = targa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.immatricolazioni.id_moto
	 * @return  the value of public.immatricolazioni.id_moto
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public Integer getIdMoto() {
		return idMoto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.immatricolazioni.id_moto
	 * @param idMoto  the value for public.immatricolazioni.id_moto
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public void setIdMoto(Integer idMoto) {
		this.idMoto = idMoto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.immatricolazioni.data_immatricolazione
	 * @return  the value of public.immatricolazioni.data_immatricolazione
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public Date getDataImmatricolazione() {
		return dataImmatricolazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.immatricolazioni.data_immatricolazione
	 * @param dataImmatricolazione  the value for public.immatricolazioni.data_immatricolazione
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public void setDataImmatricolazione(Date dataImmatricolazione) {
		this.dataImmatricolazione = dataImmatricolazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.immatricolazioni
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", idImmatricolazione=").append(idImmatricolazione);
		sb.append(", targa=").append(targa);
		sb.append(", idMoto=").append(idMoto);
		sb.append(", dataImmatricolazione=").append(dataImmatricolazione);
		sb.append("]");
		return sb.toString();
	}
}