package com.riccardo.models;

import java.util.ArrayList;
import java.util.List;

public class MotoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.moto
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.moto
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.moto
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.moto
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public MotoExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.moto
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.moto
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.moto
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.moto
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.moto
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.moto
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.moto
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.moto
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.moto
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.moto
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.moto
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdMotoIsNull() {
			addCriterion("id_moto is null");
			return (Criteria) this;
		}

		public Criteria andIdMotoIsNotNull() {
			addCriterion("id_moto is not null");
			return (Criteria) this;
		}

		public Criteria andIdMotoEqualTo(Integer value) {
			addCriterion("id_moto =", value, "idMoto");
			return (Criteria) this;
		}

		public Criteria andIdMotoNotEqualTo(Integer value) {
			addCriterion("id_moto <>", value, "idMoto");
			return (Criteria) this;
		}

		public Criteria andIdMotoGreaterThan(Integer value) {
			addCriterion("id_moto >", value, "idMoto");
			return (Criteria) this;
		}

		public Criteria andIdMotoGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_moto >=", value, "idMoto");
			return (Criteria) this;
		}

		public Criteria andIdMotoLessThan(Integer value) {
			addCriterion("id_moto <", value, "idMoto");
			return (Criteria) this;
		}

		public Criteria andIdMotoLessThanOrEqualTo(Integer value) {
			addCriterion("id_moto <=", value, "idMoto");
			return (Criteria) this;
		}

		public Criteria andIdMotoIn(List<Integer> values) {
			addCriterion("id_moto in", values, "idMoto");
			return (Criteria) this;
		}

		public Criteria andIdMotoNotIn(List<Integer> values) {
			addCriterion("id_moto not in", values, "idMoto");
			return (Criteria) this;
		}

		public Criteria andIdMotoBetween(Integer value1, Integer value2) {
			addCriterion("id_moto between", value1, value2, "idMoto");
			return (Criteria) this;
		}

		public Criteria andIdMotoNotBetween(Integer value1, Integer value2) {
			addCriterion("id_moto not between", value1, value2, "idMoto");
			return (Criteria) this;
		}

		public Criteria andModelloIsNull() {
			addCriterion("modello is null");
			return (Criteria) this;
		}

		public Criteria andModelloIsNotNull() {
			addCriterion("modello is not null");
			return (Criteria) this;
		}

		public Criteria andModelloEqualTo(String value) {
			addCriterion("modello =", value, "modello");
			return (Criteria) this;
		}

		public Criteria andModelloNotEqualTo(String value) {
			addCriterion("modello <>", value, "modello");
			return (Criteria) this;
		}

		public Criteria andModelloGreaterThan(String value) {
			addCriterion("modello >", value, "modello");
			return (Criteria) this;
		}

		public Criteria andModelloGreaterThanOrEqualTo(String value) {
			addCriterion("modello >=", value, "modello");
			return (Criteria) this;
		}

		public Criteria andModelloLessThan(String value) {
			addCriterion("modello <", value, "modello");
			return (Criteria) this;
		}

		public Criteria andModelloLessThanOrEqualTo(String value) {
			addCriterion("modello <=", value, "modello");
			return (Criteria) this;
		}

		public Criteria andModelloLike(String value) {
			addCriterion("modello ilike", value, "modello");
			return (Criteria) this;
		}

		public Criteria andModelloNotLike(String value) {
			addCriterion("modello not like", value, "modello");
			return (Criteria) this;
		}

		public Criteria andModelloIn(List<String> values) {
			addCriterion("modello in", values, "modello");
			return (Criteria) this;
		}

		public Criteria andModelloNotIn(List<String> values) {
			addCriterion("modello not in", values, "modello");
			return (Criteria) this;
		}

		public Criteria andModelloBetween(String value1, String value2) {
			addCriterion("modello between", value1, value2, "modello");
			return (Criteria) this;
		}

		public Criteria andModelloNotBetween(String value1, String value2) {
			addCriterion("modello not between", value1, value2, "modello");
			return (Criteria) this;
		}

		public Criteria andCcIsNull() {
			addCriterion("cc is null");
			return (Criteria) this;
		}

		public Criteria andCcIsNotNull() {
			addCriterion("cc is not null");
			return (Criteria) this;
		}

		public Criteria andCcEqualTo(Integer value) {
			addCriterion("cc =", value, "cc");
			return (Criteria) this;
		}

		public Criteria andCcNotEqualTo(Integer value) {
			addCriterion("cc <>", value, "cc");
			return (Criteria) this;
		}

		public Criteria andCcGreaterThan(Integer value) {
			addCriterion("cc >", value, "cc");
			return (Criteria) this;
		}

		public Criteria andCcGreaterThanOrEqualTo(Integer value) {
			addCriterion("cc >=", value, "cc");
			return (Criteria) this;
		}

		public Criteria andCcLessThan(Integer value) {
			addCriterion("cc <", value, "cc");
			return (Criteria) this;
		}

		public Criteria andCcLessThanOrEqualTo(Integer value) {
			addCriterion("cc <=", value, "cc");
			return (Criteria) this;
		}

		public Criteria andCcIn(List<Integer> values) {
			addCriterion("cc in", values, "cc");
			return (Criteria) this;
		}

		public Criteria andCcNotIn(List<Integer> values) {
			addCriterion("cc not in", values, "cc");
			return (Criteria) this;
		}

		public Criteria andCcBetween(Integer value1, Integer value2) {
			addCriterion("cc between", value1, value2, "cc");
			return (Criteria) this;
		}

		public Criteria andCcNotBetween(Integer value1, Integer value2) {
			addCriterion("cc not between", value1, value2, "cc");
			return (Criteria) this;
		}

		public Criteria andAnnoIsNull() {
			addCriterion("anno is null");
			return (Criteria) this;
		}

		public Criteria andAnnoIsNotNull() {
			addCriterion("anno is not null");
			return (Criteria) this;
		}

		public Criteria andAnnoEqualTo(String value) {
			addCriterion("anno =", value, "anno");
			return (Criteria) this;
		}

		public Criteria andAnnoNotEqualTo(String value) {
			addCriterion("anno <>", value, "anno");
			return (Criteria) this;
		}

		public Criteria andAnnoGreaterThan(String value) {
			addCriterion("anno >", value, "anno");
			return (Criteria) this;
		}

		public Criteria andAnnoGreaterThanOrEqualTo(String value) {
			addCriterion("anno >=", value, "anno");
			return (Criteria) this;
		}

		public Criteria andAnnoLessThan(String value) {
			addCriterion("anno <", value, "anno");
			return (Criteria) this;
		}

		public Criteria andAnnoLessThanOrEqualTo(String value) {
			addCriterion("anno <=", value, "anno");
			return (Criteria) this;
		}

		public Criteria andAnnoLike(String value) {
			addCriterion("anno like", value, "anno");
			return (Criteria) this;
		}

		public Criteria andAnnoNotLike(String value) {
			addCriterion("anno not like", value, "anno");
			return (Criteria) this;
		}

		public Criteria andAnnoIn(List<String> values) {
			addCriterion("anno in", values, "anno");
			return (Criteria) this;
		}

		public Criteria andAnnoNotIn(List<String> values) {
			addCriterion("anno not in", values, "anno");
			return (Criteria) this;
		}

		public Criteria andAnnoBetween(String value1, String value2) {
			addCriterion("anno between", value1, value2, "anno");
			return (Criteria) this;
		}

		public Criteria andAnnoNotBetween(String value1, String value2) {
			addCriterion("anno not between", value1, value2, "anno");
			return (Criteria) this;
		}

		public Criteria andPrezzoIsNull() {
			addCriterion("prezzo is null");
			return (Criteria) this;
		}

		public Criteria andPrezzoIsNotNull() {
			addCriterion("prezzo is not null");
			return (Criteria) this;
		}

		public Criteria andPrezzoEqualTo(Integer value) {
			addCriterion("prezzo =", value, "prezzo");
			return (Criteria) this;
		}

		public Criteria andPrezzoNotEqualTo(Integer value) {
			addCriterion("prezzo <>", value, "prezzo");
			return (Criteria) this;
		}

		public Criteria andPrezzoGreaterThan(Integer value) {
			addCriterion("prezzo >", value, "prezzo");
			return (Criteria) this;
		}

		public Criteria andPrezzoGreaterThanOrEqualTo(Integer value) {
			addCriterion("prezzo >=", value, "prezzo");
			return (Criteria) this;
		}

		public Criteria andPrezzoLessThan(Integer value) {
			addCriterion("prezzo <", value, "prezzo");
			return (Criteria) this;
		}

		public Criteria andPrezzoLessThanOrEqualTo(Integer value) {
			addCriterion("prezzo <=", value, "prezzo");
			return (Criteria) this;
		}

		public Criteria andPrezzoIn(List<Integer> values) {
			addCriterion("prezzo in", values, "prezzo");
			return (Criteria) this;
		}

		public Criteria andPrezzoNotIn(List<Integer> values) {
			addCriterion("prezzo not in", values, "prezzo");
			return (Criteria) this;
		}

		public Criteria andPrezzoBetween(Integer value1, Integer value2) {
			addCriterion("prezzo between", value1, value2, "prezzo");
			return (Criteria) this;
		}

		public Criteria andPrezzoNotBetween(Integer value1, Integer value2) {
			addCriterion("prezzo not between", value1, value2, "prezzo");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.moto
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.moto
     *
     * @mbg.generated do_not_delete_during_merge Tue Oct 10 17:23:51 CEST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}