package com.riccardo.models;

public class Moto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.moto.id_moto
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	private Integer idMoto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.moto.modello
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	private String modello;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.moto.cc
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	private Integer cc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.moto.anno
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	private String anno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.moto.prezzo
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	private Integer prezzo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.moto.id_moto
	 * @return  the value of public.moto.id_moto
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public Integer getIdMoto() {
		return idMoto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.moto.id_moto
	 * @param idMoto  the value for public.moto.id_moto
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public void setIdMoto(Integer idMoto) {
		this.idMoto = idMoto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.moto.modello
	 * @return  the value of public.moto.modello
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public String getModello() {
		return modello;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.moto.modello
	 * @param modello  the value for public.moto.modello
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public void setModello(String modello) {
		this.modello = modello;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.moto.cc
	 * @return  the value of public.moto.cc
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public Integer getCc() {
		return cc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.moto.cc
	 * @param cc  the value for public.moto.cc
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public void setCc(Integer cc) {
		this.cc = cc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.moto.anno
	 * @return  the value of public.moto.anno
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public String getAnno() {
		return anno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.moto.anno
	 * @param anno  the value for public.moto.anno
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public void setAnno(String anno) {
		this.anno = anno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.moto.prezzo
	 * @return  the value of public.moto.prezzo
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public Integer getPrezzo() {
		return prezzo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.moto.prezzo
	 * @param prezzo  the value for public.moto.prezzo
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	public void setPrezzo(Integer prezzo) {
		this.prezzo = prezzo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.moto
	 * @mbg.generated  Sat Oct 21 12:44:24 CEST 2023
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", idMoto=").append(idMoto);
		sb.append(", modello=").append(modello);
		sb.append(", cc=").append(cc);
		sb.append(", anno=").append(anno);
		sb.append(", prezzo=").append(prezzo);
		sb.append("]");
		return sb.toString();
	}
}